from tkinter import *
root=Tk()
but = Button(root, text="Отправить", bg="lightblue")
lab = Label(root, text="Ваш адрес")
ent = Entry(root,width=20,bd=3)
lab2 = Label(root,text="Коментарий")
text = Text(root,width=25, height=7, wrap=WORD)

lab.pack()
ent.pack()
lab2.pack()
text.pack()
but.pack()
root.mainloop()

root2=Tk()
labe= Label(root2, text="Сколько штук?")
var=IntVar()
var.set(0)
rad0 = Radiobutton(root2,text=" 0-10", variable=var,value=0)
rad1 = Radiobutton(root2,text="11-20", variable=var,value=1)
rad2 = Radiobutton(root2,text="21-30", variable=var,value=2)
rad3 = Radiobutton(root2,text="31-40", variable=var,value=3)

labe2=Label(root2,text="Какого цвета?")
c1 = IntVar()
c2 = IntVar()
c3 = IntVar()
c4 = IntVar()
c1 = Checkbutton(root2,text="RED",bg='red')
c2 = Checkbutton(root2,text="BLUE",bg='blue')
c3 = Checkbutton(root2,text="GREEN",bg='lightgreen')
c4 = Checkbutton(root2,text="YELLOW",bg='yellow')

labe.pack()
rad0.pack()
rad1.pack()
rad2.pack()
rad3.pack()
labe2.pack()
c1.pack()
c2.pack()
c3.pack()
c4.pack()
root2.mainloop()